### ISSUE TITLE
"Failed to rebuild native modules" on v1.52

### ISSUE THREAD

**Issue by smcmanusllb** [ibmdb/vscode-extension#25] opened 2021-01-25 19:31 UTC
Sorry to ask this again, but I can't figure out what the problem is based on the answers to similar "issues".  I'm on v1.52.1 and tried to connect but got the above error.  It also won't let me upload the screenshot, so here's the copy:

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

I saw the note about running Db2: Rebuild Native Modules when a new version comes out so I tried that but it fails too.

Any assistance would be greatly appreciated

**Comment by akhilravuri1** [comment] 2021-01-28 16:25
Hi @smcmanusllb,
Sorry for the late reply.
Run node -v, npm -v in your cmd and paste the output.

Thanks,
Akhil

**Comment by shreddy1** [comment] 2021-02-07 19:36
Hi @akhilravuri1 ,
Even I'm getting the same error on windows laptop. I'm also getting this error: 
Command 'Db2: Manage Connection Profiles' resulted in an error (command 'extension.Db2ManageConnProfiles' not found)

I have installed the latest version of node and npm. But I'm still not able to connect to db2.

**Comment by akhilravuri1** [comment] 2021-02-08 06:05
Hi @shreddy1 

what is your vscode version, npm, node?

If you are in windows please run code --version, node -v, npm -v in the cmd and paste the output.

Thanks,
Akhil

**Comment by shreddy1** [comment] 2021-02-08 12:34
Hi @akhilravuri1 
vscode: 1.53.0
npm: 7.5.2
node: v15.8.0

**Comment by akhilravuri1** [comment] 2021-02-08 12:39
Hi @shreddy1 

Now uninstall the extension and close the vscode and reopen it and install it again.

Even now if you are facing the issue please send us the log output.

How to take logs?

Please see this https://github.com/ibmdb/vscode-extension/issues/20#issuecomment-694261954

Thanks,
Akhil

**Comment by shreddy1** [comment] 2021-02-08 12:44
@akhilravuri1 do I need to uninstall Db2connect?

**Comment by akhilravuri1** [comment] 2021-02-08 12:46
This is the first time you installed Db2Connect or you were using it for a long time and it stopped working only when you updated you 1.53?

**Comment by shreddy1** [comment] 2021-02-08 12:46
It's my first time I installed Db2connect

**Comment by akhilravuri1** [comment] 2021-02-08 12:47
Okay...uninstall the Db2Connect extension and install it again

**Comment by akhilravuri1** [comment] 2021-02-08 12:48
if any issue occurs please see the log comment to paste the log here

**Comment by shreddy1** [comment] 2021-02-08 12:53
[2/8/2021 7:53:34 AM] Proceeding to rebuild native modules

[2/8/2021 7:53:34 AM] No ibm_db found...

Running npm install in c:\Users\shreddy\.vscode\extensions\ibm.db2connect-2.0.0...

npm

 ERR! code 128

npm ERR!

 command failed

npm ERR! command git ls-remote ssh://git@github.com/ibmdb/node-ibm_db.git

npm ERR! Host key verification failed.

npm 

ERR! fatal: Could not read from remote repository.

npm ERR! 

npm

 ERR! Please make sure you have the correct access rights

npm 

ERR! and the repository exists.

 

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\shreddy\AppData\Local\npm-cache\_logs\2021-02-08T12_47_50_628Z-debug.log

[2/8/2021 7:47:50 AM] ibm_db installation failed with code: 128

Error: Failed to execute command "npm" with  arguments "install" return code 128

**Comment by akhilravuri1** [comment] 2021-02-08 12:57
can you run In normal command prompt?
```
npm install git+https://github.com/ibmdb/node-ibm_db.git#vscode
```

Thanks,
Akhil

**Comment by shreddy1** [comment] 2021-02-08 13:05
C:\Users\shreddy>npm install git+https://github.com/ibmdb/node-ibm_db.git#vscode

npm ERR! code 128

npm ERR! command failed

npm ERR! command git ls-remote ssh://git@github.com/ibmdb/node-ibm_db.git

npm ERR! Host key verification failed.

npm ERR! fatal: Could not read from remote repository.

npm ERR!

npm ERR! Please make sure you have the correct access rights

npm ERR! and the repository exists.

 

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\shreddy\AppData\Local\npm-cache\_logs\2021-02-08T13_03_18_463Z-debug.log

**Comment by akhilravuri1** [comment] 2021-02-08 13:09
Looks like there is some issue with your git I am trying to reproduce it. Maybe because of access or port I guess.

**Comment by shreddy1** [comment] 2021-02-08 13:18
So what should I do now?

**Comment by akhilravuri1** [comment] 2021-02-08 13:48
Create a new ssh key and use it.

**Comment by shreddy1** [comment] 2021-02-08 13:56
create new ssh on cmd prompt? and then what do I do after creating a new ssh key?

**Comment by akhilravuri1** [comment] 2021-02-09 05:29
https://docs.gitlab.com/ee/ssh/README.html

check this on how to create an ssh key

**Comment by akhilravuri1** [comment] 2021-03-19 04:14
Closing this as the user did not respond.

**Closed by akhilravuri1** 2021-03-19 04:14 UTC
