### ISSUE TITLE
Command 'db2: Manage Connection Profiles' resulted in an error (command extension.Db2ManageConnProfiles not found)

### ISSUE THREAD

**Issue by herr6374** [ibmdb/vscode-extension#21] opened 2020-09-25 12:49 UTC
- Platform: Windows

- vscode Version:
- Is node.js and npm installed: yes/no
- node.js and npm Version: 12.14.1
- 
 
![Capture](https://user-images.githubusercontent.com/70452622/94268658-7e7bff00-ff0b-11ea-89c4-cab7cff71b90.PNG)

Hello, I am having an issue connecting to an IBM db2 database. I have newly installed VS Code. The above image is the error I am getting. Further information about my VS Code is:

Version: 1.49.2
Electron: 9.2.1
Chrome: not relevant I don't think 
Node.js: 12.14.1
V8: 8.3.110.13-electron0
OS: Windows_NT x64 10.0

**Comment by akhilravuri1** [comment] 2020-09-25 12:54
Hi @herr6374,

Please uninstall the extension and close the vscode and open and install it again.

if you face the error, please paste the log.

how to get the log?

see..this comment..https://github.com/ibmdb/vscode-extension/issues/20#issuecomment-694261954

Thanks,
Akhil

**Comment by herr6374** [comment] 2020-09-25 12:58
Hello, thank you for the prompt response. I meant to include that above, I have done this a few times already (uninstalling, closing, and installing again. 

[9/25/2020 8:58:00 AM] Proceeding to rebuild native modules
[9/25/2020 8:58:00 AM] No ibm_db found...
Running npm install,ibm_db in c:\Users\Logan\.vscode\extensions\ibm.db2connect-win-1.1.0...
'npm' is not recognized as an internal or external command,
operable program or batch file.
[9/25/2020 8:58:00 AM] ibm_db installation failed with code: 1
Error: Failed to execute command "npm" with  arguments "install, ibm_db" return code 1

**Comment by akhilravuri1** [comment] 2020-09-25 13:01
from the log, I see npm is not recognized which means npm is not installed.
npm comes with a node installation.

If node is installed please open a command prompt and run...

```
node -v
```
```
npm -v
```
and paste the output.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2020-09-25 13:03
> * Is node.js and npm installed: yes/no

Here you haven't told us that node is installed or not.

Thanks,
Akhil

**Comment by herr6374** [comment] 2020-09-25 13:20
![Capture](https://user-images.githubusercontent.com/70452622/94271858-3ca18780-ff10-11ea-9121-356cf8617619.PNG)

Sorry about that.. bear with me I am still learning. I was under the impression that because when I click "about" and it says node.js: 12.14.1 so was thinking this meant it was installed.

**Comment by akhilravuri1** [comment] 2020-09-25 13:23
Hi @herr6374 

Not a problem at all.
Please install node from https://nodejs.org/download/release/v12.14.1/

Thanks,
Akhil

**Comment by herr6374** [comment] 2020-09-25 13:36
The new
![Capture 2](https://user-images.githubusercontent.com/70452622/94273626-a6229580-ff12-11ea-9b86-0bf5e2fafa8f.PNG)
![Capture 3](https://user-images.githubusercontent.com/70452622/94273628-a6229580-ff12-11ea-966a-4e26fa7d6e8c.PNG)
![Capture](https://user-images.githubusercontent.com/70452622/94273629-a6229580-ff12-11ea-8331-02163b1b784f.PNG)


 error now...

**Comment by akhilravuri1** [comment] 2020-09-25 13:54
Hi @herr6374 

try git --version

and paste the output.

Thanks,
Akhil

**Comment by herr6374** [comment] 2020-09-25 13:55
![Capture](https://user-images.githubusercontent.com/70452622/94275689-424d9c00-ff15-11ea-8e2d-b5831614f714.PNG)

**Comment by akhilravuri1** [comment] 2020-09-25 13:56
Sorry..npm uses git to download the packages so you need git also in your system.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2020-09-25 13:59
You can install  git from here https://git-scm.com/download/win
and make sure that git is working from cmd.

Thanks,
Akhil

**Comment by herr6374** [comment] 2020-09-25 14:05
Awesome it is working now. Thank you so much for your patience and assistance.

Thank you,

Logan

**Comment by akhilravuri1** [comment] 2020-09-25 14:07
no problem.

closing the issue as the user confirmed the issue is solved.

Thanks,
Akhil

**Closed by akhilravuri1** 2020-09-25 14:07 UTC
