### ISSUE TITLE
Failed to rebuild native modules

### ISSUE THREAD

**Issue by lindonma** [ibmdb/vscode-extension#16] opened 2020-05-05 13:39 UTC
My node version is v12.8.1 and npm version is 6.7.0, and the OUTPUT of Db2Connect says "The Module ~/.vscode-server/extensions/ibm.db2connect-linux-1.1.0/node_modules/ibm_db/build/Release/odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 75. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)." Please Help.

**Comment by akhilravuri1** [comment] 2020-05-05 13:45
Hi @lindonma 

Please provide vscode version information.
Take a screenshot like this and post it.
![image](https://user-images.githubusercontent.com/32290825/81073090-bbb40600-8f04-11ea-96f9-3d700db0ebfb.png)


Thanks,
Akhil

**Comment by lindonma** [comment] 2020-05-05 13:53
Here is my vscode version information.
![捕获](https://user-images.githubusercontent.com/34507558/81073851-cf6a6700-8f1a-11ea-84df-59d37b9963b9.PNG)

**Comment by akhilravuri1** [comment] 2020-05-05 14:06
Hi @lindonma 
I see Linux file in the first comment and now you are pasting windows platform screenshot.

Thanks,
Akhil

**Comment by lindonma** [comment] 2020-05-05 14:20
I installed the extension in a linux container using vscode's remote container development.

**Comment by akhilravuri1** [comment] 2020-05-05 14:34
Hi @lindonma 

I am very new to remote containers. 
If you are installing the extension on Linux container the which node js version is installed in that container.

From the node.js list (https://nodejs.org/en/download/releases/), I can't find 75 NODE_MODULE_VERSION.

Thanks,
Akhil

**Comment by lindonma** [comment] 2020-05-05 14:51
Hi @akhilravuri1 
I konw nothing about nodejs, so I'm also very confused. Anyway, thanks for your help. Maybe I should use some other db2 client tools.

**Comment by akhilravuri1** [comment] 2020-05-05 14:54
Hi @lindonma 

If you are installing any extension on a container then it compiles with that node.js installed in that container.

so which version of node.js is installed in that container.

Thanks,
Akhil

**Comment by lindonma** [comment] 2020-05-05 15:07
Hi @akhilravuri1 
I only installed nodejs(v12.8.1) and npm(6.7.0) in the Linux container, I didn't install them on Windows.

**Comment by akhilravuri1** [comment] 2020-05-05 15:59
Hi @akhilravuri1 
Give me some time I will try it.

Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2020-05-11 03:40
Hi @lindonma 

Not able to reproduce the issue in the Linux environment.

Trying to reproduce it in the container. Are you using Remote Container (VS Code Extension) ?

Thanks,
Akhil

**Comment by lannuttia** [comment] 2020-06-19 19:43
I believe that that is the environment that @lindonma was running in. I am using the Remote Containers VS Code extension and I am also seeing this same issue. I am personally running into this issue running a development container that uses a `mcr.microsoft.com/vscode/devcontainers/base:debian-9` base image. While there is definitely more to my environment than just that, I believe that just attempting to use the extension with the previously mentioned base image should be enough to reproduce the issue.

If you still cannot reproduce this issue, I can see about cobbling together some environment where this issue can be reproduced. Just let me know if you need any more information.

**Comment by huntsfromshadow** [comment] 2020-09-24 17:40
I have had this happening as well.

Error: The module '/home/xxxx/.vscode-server/extensions/ibm.db2connect-linux-1.1.0/node_modules/ibm_db/build/Release/odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 80. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

I'm running VSCode in windows but workting through WSL2 running Ubuntu - 20.04
Installed in ubuntu is node v14.12.0.

If I manuall go to Error: The module '/home/xxxx/.vscode-server/extensions/ibm.db2connect-linux-1.1.0/node_modules/ and rebuild it does fine.

But if I try to run any db2 commands it tries to rebuild the native exention again and throws the same error.

**Comment by bimalkjha** [comment] 2020-09-24 19:13
@huntsfromshadow Go to Help->About in your vscode as mentioned in [this](https://github.com/ibmdb/vscode-extension/issues/16#issuecomment-624064552) comment and check the node.js version. It should be 12. 8.1 or 12.14.1 depending on version of vscode. You need to install the same version of node.js in your system and then use `npm install`. Thanks.

**Comment by akhilravuri1** [comment] 2020-10-16 06:55
@huntsfromshadow is your issue resolved?

**Comment by huntsfromshadow** [comment] 2020-10-16 14:51
@akhilravuri1 I am afraid work has made me move to other projects that don't involve DB@. So this is resolved in that I can't get back to it for the forseeable future.

**Comment by lannuttia** [comment] 2020-10-16 14:52
@akhilravuri1 I am still seeing this issue as of today.

**Comment by akhilravuri1** [comment] 2020-10-16 15:10
Hi @lannuttia 

Please take the log and share it.

How to take the log?
please see this https://github.com/ibmdb/vscode-extension/issues/20#issuecomment-694261954

Thanks,
Akhil

**Comment by lannuttia** [comment] 2020-10-16 15:35
> [10/16/2020 3:32:34 PM] Proceeding to rebuild native modules
[10/16/2020 3:32:34 PM] Cleaning up the current ibm_db
Running npm install,ibm_db in /home/vscode/.vscode-server-insiders/extensions/ibm.db2connect-linux-1.1.0...
Error: spawn npm ENOENT

**Comment by akhilravuri1** [comment] 2020-10-16 16:02
Can you please the full log?

Thanks,
Akhil

**Comment by saisomu4somu** [comment] 2020-10-19 09:43
Hi @akhilravuri1 

Facing same issue. Please review below and see if you can help.

**VsCode:**
![image](https://user-images.githubusercontent.com/34907289/96428247-2a6bee00-121d-11eb-859e-2a151ba9406d.png)

**-------------------------------------**
**Log**
**-------------------------------------**
[10/19/2020 3:06:25 PM] Proceeding to rebuild native modules
[10/19/2020 3:06:25 PM] No ibm_db found...
Running npm install,ibm_db in c:\Users\ss\.vscode\extensions\ibm.db2connect-win-1.1.0...
npm
 
ERR! code ENOENT
npm 
ERR! syscall
 spawn git
npm
 ERR! path git
npm ERR! errno ENOENT
npm
 ERR! enoent
 Error while executing:
npm 
ERR! enoent undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
npm ERR! 
enoent 
npm ERR! enoent
 
npm ERR! 
enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm
 ERR!
 A complete log of this run can be found in:
npm ERR!
     C:\Users\ss\AppData\Roaming\npm-cache\_logs\2020-10-19T09_36_27_586Z-debug.log
[10/19/2020 3:06:27 PM] ibm_db installation failed with code: 1
Error: Failed to execute command "npm" with  arguments "install, ibm_db" return code 1


**-------------------------------------**
**2020-10-19T09_36_27_586Z-debug.log**
**-------------------------------------**
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ibm_db'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose npm-session fec837ba923c2fa3
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for ibm_db@git+https://github.com/ibmdb/node-ibm_db.git#vscode Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 3354ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
10 verbose stack     at onErrorNT (internal/child_process.js:469:16)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
11 verbose cwd c:\Users\ss\.vscode\extensions\ibm.db2connect-win-1.1.0
12 verbose Windows_NT 10.0.18363
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ibm_db"
14 verbose node v12.19.0
15 verbose npm  v6.14.8
16 error code ENOENT
17 error syscall spawn git
18 error path git
19 error errno ENOENT
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ 1, true ]

**Comment by akhilravuri1** [comment] 2020-10-19 09:53
Hi @saisomu4somu 

Looks like your npm is unable to reach the servers. 
Please reinstall the node or run npm cache clean and try again.

Thanks,
Akhil

**Comment by saisomu4somu** [comment] 2020-10-19 10:44
Hi @akhilravuri1 

Tried both but facing same issue. Any other possible ways to fix this?

Thanks
Soma

**Comment by bimalkjha** [comment] 2020-10-22 09:15
@saisomu4somu Open a windows command prompt and run below command, share the result:
```
node -v
npm install ibm_db@git+https://github.com/ibmdb/node-ibm_db.git#vscode
```

**Comment by saisomu4somu** [comment] 2020-10-22 13:48
> @saisomu4somu Open a windows command prompt and run below command, share the result:
> 
> ```
> node -v
> npm install ibm_db@git+https://github.com/ibmdb/node-ibm_db.git#vscode
> ```

Hi @bimalkjha 

Thanks for looking into this. Please find below result.

C:\Users\ss>node -v
v12.14.1

C:\Users\ss>npm install ibm_db@git+https://github.com/ibmdb/node-ibm_db.git#vscode
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ss\AppData\Roaming\npm-cache\_logs\2020-10-22T13_42_49_899Z-debug.log

**2020-10-22T13_42_49_899Z-debug.log**
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ibm_db@git+https://github.com/ibmdb/node-ibm_db.git#vscode'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose config Skipping project config: C:\Users\ss/.npmrc. (matches userconfig)
5 verbose npm-session c55504bd784a4d5b
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for ibm_db@git+https://github.com/ibmdb/node-ibm_db.git#vscode Error while executing:
8 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData spawn git ENOENT
9 timing stage:rollbackFailedOptional Completed in 3ms
10 timing stage:runTopLevelLifecycles Completed in 496ms
11 verbose stack Error: spawn git ENOENT
11 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
11 verbose stack     at onErrorNT (internal/child_process.js:456:16)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:81:21)
12 verbose cwd C:\Users\ss
13 verbose Windows_NT 10.0.18363
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ibm_db@git+https://github.com/ibmdb/node-ibm_db.git#vscode"
15 verbose node v12.14.1
16 verbose npm  v6.13.4
17 error code ENOENT
18 error syscall spawn git
19 error path git
20 error errno ENOENT
21 error enoent Error while executing:
21 error enoent undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
21 error enoent
21 error enoent
21 error enoent spawn git ENOENT
22 error enoent This is related to npm not being able to find a file.
23 verbose exit [ 1, true ]

**Comment by akhilravuri1** [comment] 2020-10-22 13:55
Hi @saisomu4somu 

From the log, we can see that npm is unable to access git.
From the browser can you access this link https://github.com/ibmdb/node-ibm_db.git#vscode

Thanks,
Akhil

**Comment by saisomu4somu** [comment] 2020-10-22 14:09
> Hi @saisomu4somu
> 
> From the log, we can see that npm is unable to access git.
> From the browser can you access this link https://github.com/ibmdb/node-ibm_db.git#vscode
> 
> Thanks,
> Akhil

Hi Akhil (@akhilravuri1 )

Yes, able to access referred link through browser :-(

![image](https://user-images.githubusercontent.com/34907289/96883621-3dd9bc00-149e-11eb-8922-c7fd81541f9e.png)

Thanks,
Soma

**Comment by bimalkjha** [comment] 2020-10-22 17:39
@saisomu4somu Such issues happens due to proxy setup in the system. Please share the output below commands from windows command prompt:
```
nmp config get proxy
echo %http-proxy%
echo %https-proxy%
```
If any command print result, you need to clear that. Then try npm install command, it should work.
Similar issues are discussed in these links: [here](https://javascriptio.com/view/1277714/how-to-fix-npm-err-cannot-read-property-startswith-of-null) and [here](https://github.com/npm/npm/issues/19719#issuecomment-377185612). Please go through it and try the solutions. Thanks.

**Comment by saisomu4somu** [comment] 2020-10-23 07:28
Hi @bimalkjha  

Nothing returned from all three commands.

C:\Users\ss>npm config get proxy
null

C:\Users\ss>echo %http-proxy%
%http-proxy%

C:\Users\ss>echo %https-proxy%
%https-proxy%

Also, followed steps suggested in links shared but no luck. Only thing didn't try is turning off windows defender due to org restriction.

Finally, Tried below approach and it worked for now.

_Downloaded tar.tz file (ibm_db v2.7.1) from https://github.com/ibmdb/node-ibm_db/releases and installed manually using npm._

Now able to use this extension successfully.

Thanks a lot @bimalkjha and @akhilravuri1 .

**Closed** 2020-12-01 05:51 UTC
